### ISSUE TITLE
Why is there discord webhooks being used?

### ISSUE THREAD

**Issue by IdkDwij** [odtheking/OdinClient#27]
In https://github.com/odtheking/OdinClient/blob/main/src/main/kotlin/me/odinclient/utils/WebUtils.kt
Line 34, you use a discord webhook
![image](https://github.com/odtheking/OdinClient/assets/94942567/9b2850fd-b36e-4eef-a414-788535d58d26)
Can I get a explaination or is this a rat?

**Comment by freebonsai** [comment]
read the code and you'll see why

**Comment by IdkDwij** [comment]
Im extremely lazy, but ill try.

**Comment by IdkDwij** [comment]
I read a bunch, good code 👍 
not a rat from what i read so yay ig

**Comment by IdkDwij** [comment]
Could you make it so arrow trajectory works on all bows?
